- .github/workflows/build-and-deploy-on-merge.yml
- .github/workflows/format-code.yml
- .github/workflows/test-and-build-on-push-branch.yml
- equinity-historical-data/kubernetes/deployments/templates/deployment.yml
- equinity-historical-data/kubernetes/deployments/templates/ingress.yml
- equinity-historical-data/kubernetes/deployments/templates/service.yml
> EMP-66: add basic GitHub actions

- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/WelcomeController.java
> EMP-67: adding a welcome controller to test app once pod is deployed

- equinity-historical-data/kubernetes/deployments/templates/service.yml
> EMP-67: Update Service Pod configuration

- .github/workflows/build-and-deploy-on-merge.yml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/.helmignore
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/Chart.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/NOTES.txt
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/_helpers.tpl
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/deployment.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/hpa.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/ingress.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/service.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/serviceaccount.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/tests/test-connection.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
> Emp 79 add helm charts deployment

- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/_environment.tpl
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/deployment.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-75)
Updated to inject database connection to pod environment variables
> Emp-75:  adding db values to enviornment

- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/TaskController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/exception/ResourceNotFoundException.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Tasks.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/TasksRepository.java
- equinity-historical-data/src/main/resources/application.yaml
- equinity-historical-data/src/test/resources/application.yaml
> EMP-75 database connection

- .github/workflows/build-and-deploy-on-merge.yml
- .github/workflows/test-and-build-on-push-branch.yml
> EMP-89: Test simplyfiying actions triggered

- .github/workflows/build-and-deploy-on-merge.yml
- .github/workflows/deploy_to.yml
- .github/workflows/test-and-build-on-push-branch.yml
> EMP-89: Refactored deploy job into reusable workflow

- .github/workflows/deploy-to.yml
> EMP-89: Test to fix token write permission of wrokflow

- .github/workflows/build-and-deploy-on-merge.yml
- .github/workflows/deploy-to.yml
> EMP-89: Try to fix workflow permission

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-89: test to fix permissions

- .github/workflows/build-and-deploy-on-merge.yml
- .github/workflows/deploy-to.yml
> EMP-89: removed a commented line

- .github/workflows/deploy-to.yml
> EMP-89: Test using namespace explicit basec on app name and environment

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-89: Refactor deployment stages to be chained uat->staging->prod

- .github/workflows/_deploy-after-uat.yml
- .github/workflows/build-and-deploy-on-merge.yml
> EMP-89: Test using separate workflow for deployment

- .github/workflows/_deploy-after-uat.yml
- equinity-historical-data/docker-compose.override.yml
> Emp 89 refactor git hub actions

- .github/workflows/_deploy-after-uat.yml
> EMP-89: Fixed type on echo placefhodler for PROD deploy

- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/_environment.tpl
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-uat.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
- equinity-historical-data/src/main/resources/application.yaml
EMP-93: Adding hibernate configuration to not replace column names andd keep the ones specified and format
> EMP-93: Adding hibernate configuration to not replace column names and keep the ones specified and format

- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-uat.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
> EMP-93: Fix helm deploy issue with booleans

- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/_environment.tpl
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-uat.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
> EMP-93: fix to helm template to force quotes on dbDebug value

- equinity-historical-data/docker-compose.override.yml
> Emp 93 list tasks poc

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Task.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/TaskType.java
> EMP-93: adding UFText 3 and 6 which were missing

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/ParentTask.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Task.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/TaskType.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/TaskTypeState.java
EMP-93: Adding outer joing for CRM14.5 (post submission) reference to office code
> EMP-93: Adding outer joing for CRM14.5 (post submission) reference to office code

- equinity-historical-data/Dockerfile
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
> Updated Dockerfile to use APK as package manager

- equinity-historical-data/Dockerfile
> Fixed type deletring traling \ character

- .github/workflows/_deploy-after-uat.yml
> EMP-101: Update GitHub action to allow deployment into PROD

- equinity-historical-data/Dockerfile
> Update AWS intall on docker image

- .gitignore
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/_environment.tpl
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-uat.yaml
- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
- equinity-historical-data/src/main/resources/application.yaml
> EMP-103: Factor out database name

- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
> EMP-144: Update Ingress rules to restrict access to MoJ IPs only

- equinity-historical-data/kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
> EMP-144:  Updated mail-to message

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/TaskController.java
- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
EMP-150: Enabled Ingress access to prod and removed redundant odf-image file
> EMP-150: Enabled Ingress access to prod and removed redundant odf-image file

- data-api/build.gradle
- data-api/open-api-specification.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/SearchController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/exception/EquinityExceptionResponseHandler.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/SearchControllerTest.java
> EMP-147: Added Open API endpoint contract and basic search controller

- data-api/open-api-specification.yml
> EMP-147: Changed provider format to be a 4 to 6 input

- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
EMP-180: Change database name to eq_prod was equinity_restore_new
> EMP-180: Change database name to eq_prod

- .github/workflows/_capture-repo-info.yml
- .github/workflows/_deploy-after-uat.yml
- .github/workflows/_deploy-to.yml
- .github/workflows/build-and-deploy-on-merge.yml
- .github/workflows/test-and-build-on-push-branch.yml
- kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/_environment.tpl
EMP-181: Adding OAuth secrets from AWS
> EMP-181: Adding OAuth secrets from AWS

- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/CrmFileController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/security/ApiClientAuthExtractor.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/security/ApiClientAuthFilter.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/security/ApiClientAuthToken.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/security/SecurityConfiguration.java
- equinity-historical-data/src/main/resources/application.yaml
- equinity-historical-data/src/test/resources/application.yaml
EMP-181: Added classes to check Authentication based on API-KEY
> EMP-181: Added classes to check Authentication based on API-KEY

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/config/CrmFormSearchCriteriaDTO.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/SearchController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/SearchService.java
> EMP-183: Add logging

- .github/actions/build-app-gradle/action.yml
- build.gradle
- equinity-historical-data/build.gradle
> EMP-184: Add SonarQ to project

- .github/workflows/_deploy-after-uat.yml
- .github/workflows/test-and-build-on-push-branch.yml
- build.gradle
- data-api/build.gradle
- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/resources/application.yaml
- equinity-historical-data/src/test/resources/application.yaml
> EMP-184: Added snyk app scan to github action

- .github/workflows/_deploy-after-uat.yml
- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Add snyk to check  docker image vulnerabilities

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Moved image tag to a string and defined an env variable

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: disable snyk docker

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Add snyk docker scan again

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Try running snyk in smae task as build image

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: try using AWS login to access image

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Adding AWS token permissions for login

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Added a shell command to explore current working directory

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Trying using relative path to access Dockerfile

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Adding more debug traces

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: No files found. Adding checkout step

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Changed dockerfile path

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Added --all-projects flag

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Trying to fix error not finding package manager to gradle.build

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Using apk as package manager

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Using pip pacakge manager

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Using docker compose

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Remove specify file

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: remove commented argument lines

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Changing flag all-projects with all-sub-projects

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Adding flag all-projects with sub-projects also in

- .github/workflows/build-and-deploy-on-merge.yml
> Emp 184 add snyk docker

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Using only file flag

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Seems token permission needs to be set to write

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Adding extra debug trace pring and policy flag

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: removed flag file becaus eit should pick up as default

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: removed checkout

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Adding checkout step again and docker image

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: remove all-projects flag

- build.gradle
> EMP-184: Test moving plugin apply to all-projects part in builkd

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: adding flag all-projects lag to githubaction

- .github/workflows/build-and-deploy-on-merge.yml
- build.gradle
> EMP-184: Adding file flqg to github action

- .github/workflows/build-and-deploy-on-merge.yml
- .github/workflows/test-and-build-on-push-branch.yml
> EMP-184: Test snyk pod for specific  sub-project

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184:l Test again all flags

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-184: Try using docker setup action

- equinity-historical-data/build.gradle
> EMP-184: Updated Open-UI version to 1.8.0 was 1.7.0

- data-api/build.gradle
- equinity-historical-data/build.gradle
> EMP-184: Test to fix vulnerability

- data-api/build.gradle
- equinity-historical-data/build.gradle
> EMP-184: Add and update version for Spring Boot related dependencies 

- Dockerfile
- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-uat.yaml
- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
> EMP-184: Amend low impact vulnerabilities detected by Snyk

- .github/workflows/_deploy-after-uat.yml
- .github/workflows/_deploy-to.yml
- .github/workflows/test-and-build-on-push-branch.yml
EMP-184: Upgrade snyk docker action version and rewrite some action labels
> EMP-184: Upgrade snyk docker action version

- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/CrmFileController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/TaskImageFilesModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileServiceTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/DateUtilTest.java
> EMP-184: force an error to test PR can not be merged on error

- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/archive/controller/SearchArchiveControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/archive/service/SearchArchiveServiceTest.java
EMP-237: Added test coverage for Archive Search
> EMP-237: Added test coverage for Archive Search

- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5ControllerTest.java
> Adding CRM5 controller tests

- data-api/open-api-specification.yml
- data-api/schemas/crm7.yml
- data-api/schemas/search.yml
> EMP-210: Add CRM7 openapi specification and refactored search in a separate file

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm5DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm5Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFileDetailsModelInterface.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFileModelInterface.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileServiceTest.java
…CRM File APIs
EMP-259: Refactor CrmFileService and Mapper for generic approach for CRM File APIs
> EMP-259: Refactor CrmFileService and Mapper for generic approach for CRM File APIs

- data-api/open-api-specification.yml
- data-api/schemas/crm4.yml
> EMP-231 crm4 api contract

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4AdditionalExpenditures.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4Expenditure.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4Model.java
> EMP-255 CRM4 api model classes

- data-api/schemas/crm4.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4QuoteModel.java
> EMP-255 alternate quotes section

- data-api/open-api-specification.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/archive/controller/SearchArchiveController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/config/CrmFormSearchCriteria.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/config/CrmFormSearchCriteriaDTO.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/SearchController.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/archive/controller/SearchArchiveControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/archive/service/SearchArchiveServiceTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/SearchControllerInputsTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/SearchServiceTest.java
EMP-325: Add profileAcceptedType to search and archive search API contract. Updated unit tests
> EMP-325: Add profileAcceptedType to search and archive search API contract. Updated unit tests

- data-api/open-api-specification.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
>  CRM 5 mior fixes

- data-api/schemas/crm14.yml
> EMP-319 crm14 & 15 contract

- data-api/open-api-specification.yml
- data-api/schemas/crmEvidenceFiles.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/config/CrmFormDetailsCriteria.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/CrmFileLinkedAttachmentMapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4AdditionalExpenditures.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm5DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm5Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmEvidenceFileModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmEvidenceFilesModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFileModelInterface.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFormDetailsModelInterface.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFormModelInterface.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/TaskImageFilesRepository.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4ControllerTest.java
EMP-332: Adding attached evidence to CRM4 and generic BE API. Some refactoring was made to better accommodate this new addition
> EMP-332: Adding attached evidence to CRM4 and generic BE API

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/exception/EquinityExceptionResponseHandler.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/CrmEvidenceFilesMapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-332: Added CRM4 Evidence file list to API response and fixed error when only 1 file is attached

- data-api/schemas/crm4.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4QuoteModel.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-303)
Fixed typos for the additionalItemDesc & additionalItemAmount fields returned by the CRM4 API.
> EMP-303: Fix typos in CRM4 API response

- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/CrmFileController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileServiceTest.java
- equinity-historical-data/src/test/resources/Crm7MockFile_5001597.txt
> EMP-343: Refactored CRM File Service to be more testable and increase coverage

- data-api/schemas/crm7.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7DetailsModel.java
EMP-368: Hotfixes court Identifier and summary waiting cost mapping
> EMP-368: Hotfixes court Identifier and summary waiting cost mapping

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14AdditionalDetails.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm15EmployerDetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm15EmployersModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-321 employer details

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/report/Crm4PeriodicalReportRepository.java
EMP-374: Minor refactoring to update Report Stored Procedure name to modern naming in LAA
> EMP-374: Minor refactoring to update Report Stored Procedure name to modern naming in LAA

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm5DetailsModel.java
[EMP-312](https://dsdmoj.atlassian.net/browse/EMP-312)
Fixed missing field `New Limit Request` defect
Fixed minor local dev issue `income2` related to EMP-321
[EMP-312]: https://dsdmoj.atlassian.net/browse/EMP-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EMP-312 - Adding missing filed - New_Limit_Request

- data-api/build.gradle
- equinity-historical-data/build.gradle
> EMP-000: Upgrade Spring Starter version due to new vulnerability detected etected

- data-api/open-api-specification.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm4PeriodicalReportController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm5UpperLimitReportController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/report/Crm5UpperLimitReportModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/report/Crm5UpperLimitReportRepository.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm5UpperLimitReportService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/ReportInputsUtil.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm5UpperLimitReportControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm4PeriodicalReportServiceLocalTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm5UpperLimitReportServiceLocalTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm5UpperLimitReportServiceMockTest.java
EMP-382: Added CRM5 Upper Limit Report API wit unit test coverage updated
> EMP-382: Added CRM5 Upper Limit Report API

- data-api/schemas/crm7.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
> EMP-392: hotfix CRM7 for missing fields in Schedule section

- data-api/schemas/crm7.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
EMP-400: Hotfix adding fields Counsel and No Counsel to costs on Schedule Of Time section
> EMP-400: Hotfix adding fields Counsel and No Counsel to costs on Schedule Of Time section

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14AdditionalDetails.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14AttachmentModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm15TblNewAttachmentsDetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm15TblNewAttachmentsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/AttachmentStoreRepository.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/Crm14AttachmentService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/Crm14AttachmentServiceTest.java
> EMP-321 CRM14 new attachments and post submission evidence

- data-api/open-api-specification.yml
EMP-383: Adding API contract for CRM14 report and minor refactoring to unify and simplify date inputs
>  EMP-383: Adding API contract for CRM14 report and minor refactoring to unify and simplify date inputs

- data-api/open-api-specification.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/config/Crm14CaseSummaryReportCriteriaDTO.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/report/Crm14CaseSummaryReportModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/report/Crm14CaseSummaryReportRepository.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm14CaseSummaryReportService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/ReportInputsUtil.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm14CaseSummaryReportServiceMockTest.java
EMP-383: Adding CRM14 Case Summary Report Service and unit tests
> EMP-383: Adding CRM14 Case Summary Report Service and unit tests

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm14CaseSummaryReportController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm14CaseSummaryReportControllerTest.java
EMP-383: Added CRM14 Report controller to enable calls to the BE API
> EMP-383: Added CRM14 Report controller to enable calls to the BE API

- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
> EMP-383: Extension of server timeout for CRM14 report 

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm14CaseSummaryReportService.java
EMP-383: Change from 1 line to 2 lines to allow logs to track time
> EMP-383: Change from 1 line to 2 lines to allow logs to track time

- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
> EMP-383: Increase max response size to 16mb to allow CRM14 report long responses

- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
> EMP-383: Change ingress body size to be unquoted

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/SearchController.java
> Emp 243 sentry setup

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14DetailsModel.java
> EMP-424 crm15 flag

- README.md
EMP-429: Updated readme file for this project
> EMP-429: Updated readme file for this project

- README.md
EMP-429: Fixed typo on repository name
> EMP-429: Fixed typo on repository name

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
> EMP-404 improve crm7 mapping

- build.gradle
- data-api/build.gradle
- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/SearchService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm14CaseSummaryReportService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm4PeriodicalReportService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm5UpperLimitReportService.java
- equinity-historical-data/src/main/resources/application.yaml
EMP-182: Add metrics prometheus micrometer
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-182)
> EMP-182: Add metrics prometheus micrometer

- equinity-historical-data/src/main/resources/application.yaml
> EMP-182: update springdoc documentation settings

- kubernetes/helm_deploy/laa-crime-equinity-historical-data/templates/service.yaml
> Emp 182 add metrics prometheus micrometer

- equinity-historical-data/build.gradle
> EMP-182: try older version of micrometer

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/config/SpringMicrometerConfig.java
…trics
EMP-182: Add override Spring Rule for micrometer to support custom metrics
> EMP-182: Add override Spring Rule for micrometer to support custom metrics

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/SearchController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm14CaseSummaryReportController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm4PeriodicalReportController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm5UpperLimitReportController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
EMP-182: Refactor to remove Sentry as a counter now that we can use micrometer for that
EMP-182: Refactor to remove Sentry as a counter now that we can use micrometer for that
> EMP-182: Refactor to remove Sentry as a counter now that we can use micrometer for that

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileServiceTest.java
- equinity-historical-data/src/test/resources/Crm4MockFile_492914.txt
Fixing defect - CRM4 API error for JSON deserialization
> EMP-440 - CRM4 - Deserialization 

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-450 fix hyphen character issue

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-450 fix ampersand issue

- data-api/schemas/crm4.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4AuthorisedAdditionalExpenditure.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4AuthorisedExpenditureModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4RelatedSubmissions.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4SubmissionModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-402 crm official use section

- data-api/schemas/crm5.yml
- data-api/schemas/crm7.yml
Fixed CRM 5 and 7 response in synch with CRM4
> EMP-465 - Defect Fix - Fixing CRM 5 and 7 respnose

- data-api/schemas/crm5.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
Fixed `client_nfa` field issue in CRM5 API response
> EMP-457 - Fix missing client_nfa field in CRM 5 API response

- .github/workflows/build-and-deploy-on-merge.yml
> EMP-469: Fixed deploy uat after removed additional test

- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-archive.yaml
> Emp 469 add archive namespace deploy

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7DetailsModel.java
EMP-478: Change data type for XML/Json field Cp_rbba_category_cw to String
> EMP-478: Change data type for XML/Json field Cp_rbba_category_cw to String

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/exception/EquinityExceptionResponseHandler.java
> EMP-477: Adding SQL Exception to the exception handler of the API

- .gitignore
- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14AdditionalDetails.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm15BankAccountDetailsModel.java
- equinity-historical-data/src/test/resources/Crm14MockFile_5001669.txt
EMP-500: hotfix to number out of range error on premium gold number and to bank accounts
> EMP-500: hotfix to number out of range error on premium gold number and to bank accounts

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
> EMP-397 crm14 missing fields

- data-api/build.gradle
- data-api/schemas/crm14.yml
- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14DetailsModel.java
- equinity-historical-data/src/test/resources/Crm14MockFile_1826833.txt
> EMP-516: Hotfix CRM14 attribute type to boolean from integer

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14AdditionalDetails.java
> EMP-517 missing partner fields

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/CrmMapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14AdditionalDetails.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/DateUtil.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/DateUtilTest.java
- equinity-historical-data/src/test/resources/Crm14MockFile_1826833.txt
- equinity-historical-data/src/test/resources/Crm14MockFile_5001817.txt
EMP-525: Changed XML Model type for Date_Of_Birth to string and added a new convertor to the mapper whilst updating DateUtils class to handle date formatter.
> EMP-525: Changed XML Model type for Date_Of_Birth to string

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
> EMP-525 crm5 firm address fix

- data-api/schemas/crm5.yml
- data-api/schemas/crmStandardProperties.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
> EMP-518: Added Standard Properties section to CRM5

- data-api/build.gradle
- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/security/ApiClientAuthFilter.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/security/SecurityConfiguration.java
- equinity-historical-data/src/main/resources/application.yaml
> EMP-521: quick style change to force new version

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14Model.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14ControllerTest.java
> Emp 527 processed attach evidencefiles

- data-api/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/security/SecurityConfiguration.java
> Emp 521 hotfix crm5 costs rounding error

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
> EMP-530 client income support field

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7DetailsModel.java
> EMP-533: Hotfix crm7 case total missing fields

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm14AttachmentModel.java
> EMP-536 processed attachments file key in lowercase

- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm14CaseSummaryReportController.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/exception/EquinityExceptionResponseHandler.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/exception/UnauthorizedUserProfileException.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/report/Crm14CaseSummaryReportModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm14CaseSummaryReportService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/ReportInputsUtil.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm14CaseSummaryReportControllerDownloadTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm14CaseSummaryReportControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm4PeriodicalReportControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/report/Crm5UpperLimitReportControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/report/Crm14CaseSummaryReportServiceMockTest.java
EMP-540: Added a new endpoint with an improved download option for report CRM14
> EMP-540: Added a new endpoint with an improved download option for report CRM14

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7ScheduleTimeSpentModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7TimeSpentModel.java
EMP-543: Added Schedule Time Spent missing table mapping
> EMP-543: Added Schedule Time Spent missing table mapping

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7DisbursementModel.java
- equinity-historical-data/src/test/resources/Crm7MockFile_5001662.txt
> EMP-535: hotmix adding missing field to table mileage

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm7TimeSpentModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
Link to story [EMP-543](https://dsdmoj.atlassian.net/browse/EMP-543)
[EMP-543]: https://dsdmoj.atlassian.net/browse/EMP-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EMP-543: hotfix added sanity check for schedule list

- data-api/schemas/crm7.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
> EMP-550 crm7 standard properties

- data-api/schemas/crm4.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
> Emp 551 crm4 standardproperties

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
EMP-523 - Defect Fix - Updating Maat_number to Maat
> EMP-523 - Defect Fix - Updating Maat_number to Maat

- data-api/schemas/crm7.yml
> EMP-550 crm 7 stand prop camel case

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm5/Crm5DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm5/Crm5Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DisbursementModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DisbursementsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7ScheduleTimeSpentModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7TimeSpentModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileServiceTest.java
EMP-553: refactored crm5 and crm7 into their own model package. 
Leaving CRM4 out for now to avoid merge conflicts whilst work on crm4 is done simultaneously. Also leaving crm14 adnd 15 for a next PR due to the amount of changes
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-553)
> EMP-553: refactored crm5 and crm7 into their own model package

- data-api/schemas/crm4.yml
- data-api/schemas/crmFurtherInformation.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFurtherInfoAttachmentsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFurtherInformationModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4ControllerTest.java
- equinity-historical-data/src/test/resources/Crm4MockFile_4795804.txt
> EMP-550 crm4 further information

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-559 crm7 laa adjustments fix

- data-api/schemas/crm7.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DisbursementModel.java
EMP-535: Added mapping to BE API response for office use only column in disbursements table
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-535)
> EMP-535: Added mapping to BE API response for office use only column in disbursements table

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
EMP-513: added mappings for travel and waiting net values in cost details section including office use part
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-513)
> EMP-513: added mappings for travel and waiting net values in cost details section including office use part

- data-api/schemas/crm4.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4AuthorisedExpenditureModel.java
> EMP-461 expenditure rate fix

- data-api/schemas/crm4.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4ExpenditureModel.java
> EMP-461 expenditure rate new fix

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
- equinity-historical-data/src/test/resources/Crm5MockFile_5001604.txt
> EMP-558: Updated mapping for decision reason according to new mapping

- data-api/schemas/crm4.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4DetailsModel.java
EMP-476: Adding missing mappings for "no vat included" and "no travel included" declarations
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-476)
> EMP-476: Adding missing mappings for "no vat included" and "no travel included" declarations

- data-api/schemas/crm5.yml
- data-api/schemas/crm7.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/CrmMapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/Crm4Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm5/Crm5DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFurtherInformationService.java
> EMP-520 further information 4,5 and 7

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4AdditionalExpenditure.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4AdditionalExpenditures.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4AuthorisedAdditionalExpenditure.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4AuthorisedExpenditureModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4ExpenditureModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4Model.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4QuoteModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4RelatedSubmissions.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4SubmissionModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFurtherInformationService.java
> EMP-553: refactored crm4 models to be in their own package

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4DetailsModel.java
> EMP-568: Apply mapping fix for CRM4

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm4Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm5Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/CrmMapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmDecisionReasonDetailsModelInterface.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm5/Crm5DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DetailsModel.java
EMP-568: Added logic fr mapping the right decision reason field based on decision result
Link to story [EMP-538](https://dsdmoj.atlassian.net/browse/EMP-538)
Link to supplement story [EMP-568](https://dsdmoj.atlassian.net/browse/EMP-568)
[EMP-538]: https://dsdmoj.atlassian.net/browse/EMP-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMP-568]: https://dsdmoj.atlassian.net/browse/EMP-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EMP-568: Added logic fr mapping the right decision reason field based on decision result

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14DetailsModel.java
> EMP-58 hascrm15 check condition

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7Controller.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/CrmFurtherInformationModelInterface.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4AdditionalExpenditures.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm5/Crm5DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm7/Crm7DetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFurtherInformationService.java
> EMP-553: refactor crm models for further information section

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-577)
> EMP-577: Adding missing mapping

- data-api/schemas/search.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/CrmFormsViewMapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/data/CrmFormViewModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/criteria/CrmFormSearchCriteria.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-586)
> EMP-586: hotfix to add sorting by submitted date (desc) and newly  requested column laaCaseRef

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4DetailsModel.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-589)
> EMP-589: hotfix to change all rate and total related fields to be Float

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14AdditionalDetails.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14DetailsModel.java
> EMP-580 show crm15 section

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14AdditionalDetails.java
EMP-601: Change numeric data types to be class (int->Integer and double->Double) to allow empty/null values
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-601)
> EMP-601: Change numeric data types to be class (int->Integer and double->Double) to allow empty/null values

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm4/Crm4ExpenditureModel.java
EMP-461: Fixed data type from int to Double
> EMP-461: Fixed data type from int to Double

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14DetailsModel.java
EMP-572  - CRM14 - Defect Fix - Legal Representation
> EMP-572  - CRM14 - Defect Fix - Legal Representation

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/criteria/CrmFormDetailsCriteria.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/criteria/input/Crm14CaseSummaryReportCriteriaDTO.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/criteria/input/CrmFormDetailsCriteriaDTO.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/ProfileAcceptedTypesUtil.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/util/ReportInputsUtil.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7ControllerTest.java
EMP-413: hotfix updated CRM Form Details to validate profile and return proper http error code 401. Refactoring
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-413)
> EMP-413: hotfix updated CRM Form Details to validate profile and return proper http error code 401

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/CrmFileController.java
> EMP-413: horfix crm-file endpoint add type parameter

- data-api/schemas/crm14.yml
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14AdditionalDetails.java
> EMP-579: Adding missing field and reordering API response

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/CrmMapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14DetailsModel.java
> EMP-610: updated mapping for idictable flag value

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14DetailsModel.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-604)
> EMP-604: Updated hasCrm15 mapping and logic rules

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-380 using ISO-8859-1  encoding used by xml in the databse

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14AdditionalDetails.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14DetailsModel.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-622)
Parent story [EMP-615](https://dsdmoj.atlassian.net/browse/EMP-615)
[EMP-615]: https://dsdmoj.atlassian.net/browse/EMP-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Emp 622 hotfix crm15 null values evidence and income

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
> EMP-490 crm 4 xml error

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/data/CrmFormViewModel.java
> EMP-626 data migration changes

- data-api/schemas/crm14.yml
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-641)
> EMP-641: Fix API response attribute type

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/data/CrmFormDetailsModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/CrmFormDetailsRepository.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileService.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm14ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm4ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm5ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/Crm7ControllerTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFileServiceTest.java
EMP-644: Refactoring TaskImageFilesModel to CrmFormDetailsModel and update data source
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-644)
> EMP-644: Refactoring TaskImageFilesModel to CrmFormDetailsModel and update data source

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm14Mapper.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/crm14/Crm14DetailsModel.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-646)
Link to story parent story [EMP-637](https://dsdmoj.atlassian.net/browse/EMP-637)
[EMP-637]: https://dsdmoj.atlassian.net/browse/EMP-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EMP-637: hotfix mapping to separation_date, was date_of_separation

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/data/CrmFormCRM14PSEMessageModel.java
> hotfix to table name

- .github/workflows/test-and-build-on-push-branch.yml
- data-api/build.gradle
- equinity-historical-data/build.gradle
EMP-653: Update project dependencies due to Snyk vulnerabilities
Link to story [EMP-653](https://dsdmoj.atlassian.net/browse/EMP-653)
[EMP-653]: https://dsdmoj.atlassian.net/browse/EMP-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EMP-653: Update project dependencies due to Snyk vulnerabilities

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/criteria/CrmFormSearchCriteria.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFormSearchServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-665)
- Fixed date range search by modifying `CrmrFormSearchCriteria.byDateSubmittedFrom` method to increment date by 1 day and to use lessThan predicate.
- Added unit test cases.
> EMP-665: Search API - no results returned for same day range

- README.md
- equinity-historical-data/build.gradle
- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values.yaml
> Emp-544 hotfix snyk vulnerabilitiy

- data-api/build.gradle
- equinity-historical-data/build.gradle
EMP-544: Update dependencies to fix low level vulnerability found by snyk
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-544)
> EMP-544: Update dependencies to fix low level vulnerability found by snyk

- .github/workflows/_deploy-after-uat.yml
- README.md
EMP-74: removal of staging namespace from pipeline and readme
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-74)
> EMP-74: removal of staging namespace from pipeline and readme

- kubernetes/helm_deploy/laa-crime-equinity-historical-data/values-prod.yaml
> Emp 74 remove staging namespace

- README.md
> EMP-74: updater readme with new links to opensearch

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/model/data/CrmFormSummaryModel.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/criteria/CrmFormSearchCriteria.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/controller/CrmFormSearchControllerInputsTest.java
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/CrmFormSearchServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-719)
> EMP-719: search by client dob

- data-api/build.gradle
- equinity-historical-data/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-726)
Updated the `org.apache.tomcat.embed:tomcat-embed-core` dependency to the recommended fix version - 10.1.31
> EMP-726: Fix snyk issue - org.apache.tomcat.embed:tomcat-embed-core version

- equinity-historical-data/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-770)
Fixed medium Snyk issues
> EMP-770: Fix medium Snyk issues

- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/EquinityHistoricalDataApplication.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/config/security/SecurityConfiguration.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/repository/CrmFormSummaryRepository.java
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/ArchiveCrmFormService.java
- equinity-historical-data/src/main/resources/application.yaml
- equinity-historical-data/src/test/java/uk/gov/justice/laa/crime/equinity/historicaldata/service/ArchiveCrmFormServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-771)
Added ArchiveCrmFormService to call archiveCrmFormData stored procedure as a scheduled task once a day.
> EMP- 771: Create scheduled task for daily archive of CRM form data

- equinity-historical-data/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-771)
> EMP-771: Change daily archive schedule to 4.30pm

- equinity-historical-data/src/main/resources/application.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-771)
Change scheduled job cron to 2am.
> EMP-771:  Change daily archive schedule to 2am

- .github/workflows/test-and-build-on-push-branch.yml
- data-api/build.gradle
- equinity-historical-data/build.gradle
- equinity-historical-data/src/main/java/uk/gov/justice/laa/crime/equinity/historicaldata/mapper/Crm7Mapper.java
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-775)
Updated CRM7Mapper to use convertToTimeSpentString to fix incorrect time field in ScheduleOfTimeSpent.
> EMP-775: Fix incorrect time in CRM7 Schedule Of Time Spent

- .github/workflows/test-and-build-on-push-branch.yml
- data-api/build.gradle
- equinity-historical-data/build.gradle
[Link to story](https://dsdmoj.atlassian.net/browse/EMP-776)
- Upgraded tomcat-embed-core version to 10.1.39
- Removed temporary fix to snyk-docker build step
> EMP-776: Fixed Snyk tomcat-embed-core issue
